"""Standalone HTML/CSV/JSON report export (no external assets, offline-safe)."""

from __future__ import annotations

from html import escape

from app import schemas
from app.lifecycle import status_color

_CSS = """
:root{--ink:#1c2733;--mut:#5b6b7c;--line:#dde5ec;--bg:#f4f7fa;--blue:#173b63;--accent:#2d6fa3}
*{box-sizing:border-box}body{font:14px/1.5 'Segoe UI',Arial,sans-serif;color:var(--ink);background:var(--bg);margin:0;padding:32px}
.wrap{max-width:1080px;margin:0 auto}
h1{font-size:22px;color:var(--blue);margin:0 0 4px}h2{font-size:15px;color:var(--blue);margin:22px 0 8px;border-bottom:2px solid var(--line);padding-bottom:4px}
.card{background:#fff;border:1px solid var(--line);border-radius:10px;padding:14px 18px;margin:10px 0}
.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}
.kv{display:flex;justify-content:space-between;padding:5px 0;border-bottom:1px solid #eef2f6}.k{color:var(--mut)}
table{width:100%;border-collapse:collapse;font-size:13px}th,td{text-align:left;padding:6px 8px;border-bottom:1px solid var(--line)}th{color:var(--mut);font-weight:600}
.pill{display:inline-block;padding:2px 10px;border-radius:12px;font-weight:700;font-size:12px}
.green{background:#e6f6ed;color:#1d7a44}.yellow{background:#fff5d9;color:#8a6d1a}.red{background:#fde9e9;color:#b33838}.blue{background:#e8f2fb;color:#1f5d8d}
.mut{color:var(--mut);font-size:12px}.tag{font-weight:600}
.mono{font-family:Consolas,monospace}
.footer{margin-top:24px;color:var(--mut);font-size:12px;text-align:center}
"""


def _pill(status: str) -> str:
    color = status_color(status)
    cls = color if color in ("green", "yellow", "red", "blue") else "blue"
    return f'<span class="pill {cls}">{escape(status)}</span>'


def part_html(report: schemas.PartReportOut) -> str:
    c = report.component
    rows = []
    for label, value in (
        ("Manufacturer", c.manufacturer),
        ("MPN", c.manufacturer_mpn),
        ("Category", c.category),
        ("Family", c.family),
        ("Package", c.package),
        ("Description", c.description),
        ("RoHS", c.rohs),
        ("REACH", c.reach),
        ("Operating voltage", c.operating_voltage),
        ("Current", c.current),
        ("Frequency", c.frequency),
        ("Temperature", c.temperature),
    ):
        rows.append(
            f'<div class="kv"><span class="k">{escape(label)}</span><span class="mono">{escape(str(value) or "-")}</span></div>'
        )

    snap_rows = ""
    for snap in sorted(c.snapshots, key=lambda s: s.checked_at, reverse=True)[:4]:
        pb = "; ".join(f"{b.qty}×{b.price}" for b in snap.price_breaks[:3]) or "-"
        qty = str(snap.available_qty) if snap.available_qty is not None else "-"
        snap_rows += (
            f'<tr><td class="tag">{escape(snap.distributor)}</td><td>{qty}</td>'
            f"<td>{escape(pb)}</td><td>{escape(snap.lead_time or '-')}</td>"
            f'<td class="mut">{snap.checked_at:%Y-%m-%d %H:%M}</td></tr>'
        )

    alt_rows = ""
    for a in report.alternatives:
        alt_rows += (
            '<tr><td class="mono tag">'
            + escape(a.mpn)
            + "</td><td>"
            + escape(a.manufacturer)
            + "</td><td>"
            + escape(a.package)
            + f'</td><td>{_pill(a.lifecycle_status)}</td><td><span class="tag">{escape(a.kind)}</span></td>'
            + f'<td>{a.score:.2f}</td><td class="mut">{"; ".join(escape(r) for r in a.reasons[:2])}</td></tr>'
        )

    breakdown = ""
    for k, sub in report.risk.breakdown.items():
        breakdown += (
            f'<div class="kv"><span class="k">{escape(k.replace("_", " ").title())}</span><span>{sub:.0%}</span></div>'
        )

    return f"""<!doctype html><html><head><meta charset="utf-8"><title>{escape(c.mpn_normalized)}</title>
    <style>{_CSS}</style></head><body><div class="wrap">
    <h1>{escape(c.mpn_normalized)} <span class="mut">{escape(c.manufacturer)}</span></h1>
    <div class="mut">Lifecycle {_pill(c.lifecycle_status)} &nbsp;•&nbsp; Confidence {report.confidence:.0%} &nbsp;•&nbsp; Verified {c.last_verified or "never"}</div>
    <div class="card"><h2>Component Record</h2>{"".join(rows)}</div>
    <div class="grid">
      <div class="card"><h2>Risk {report.risk.score}/100 · <span class="pill {"red" if report.risk.level in ("HIGH", "CRITICAL") else "green"}">{escape(report.risk.level)}</span></h2>{breakdown}</div>
      <div class="card"><h2>Distributor Snapshot</h2><table><tr><th>Vendor</th><th>Stock</th><th>Price breaks</th><th>Lead</th><th>Checked</th></tr>{snap_rows}</table></div>
    </div>
    <div class="card"><h2>Alternatives</h2>{f"<table><tr><th>MPN</th><th>Manufacturer</th><th>Package</th><th>Lifecycle</th><th>Kind</th><th>Score</th><th>Why</th></tr>{alt_rows}</table>" if alt_rows else '<div class="mut">No candidates scored.</div>'}</div>
    <div class="footer">Generated by Part Intelligence • source-backed data, no invented specifications</div>
    </div></body></html>"""


def bom_html(report: schemas.BomReportOut) -> str:
    rows = ""
    for line in report.lines:
        lc = line.component.lifecycle_status if line.component else ""
        lvl = line.risk.level if line.risk else "-"
        color = "green" if lvl == "LOW" else "yellow" if lvl == "MEDIUM" else "red"
        alts = "; ".join(a.mpn for a in line.alternatives[:3]) if line.alternatives else "-"
        rows += (
            "<tr><td>"
            + str(line.seq)
            + "</td><td>"
            + escape(line.reference)
            + "</td><td class='mono'>"
            + escape(line.mpn)
            + "</td><td>"
            + escape(line.manufacturer)
            + "</td><td>"
            + str(line.qty)
            + "</td><td>"
            + (escape(lc) if lc else "-")
            + "</td><td>"
            + (f'<span class="pill {color}">{escape(lvl)}</span>' if lvl != "-" else "-")
            + "</td><td>"
            + (f"{line.cost_estimate:.2f}" if line.cost_estimate is not None else "-")
            + "</td><td>"
            + escape(alts)
            + "</td><td class='mut'>"
            + escape("; ".join(line.errors))
            + "</td></tr>"
        )
    dist = "".join(
        f'<span class="pill {status_color(k)}">{escape(k)} {v}</span> '
        for k, v in report.lifecycle_distribution.items()
    )
    riskdist = "".join(
        f'<span class="pill {"red" if k in ("HIGH", "CRITICAL") else "yellow" if k == "MEDIUM" else "green"}">{escape(k)} {v}</span> '
        for k, v in report.risk_distribution.items()
    )
    return f"""<!doctype html><html><head><meta charset="utf-8"><title>BOM intelligence</title>
    <style>{_CSS}</style></head><body><div class="wrap">
    <h1>BOM Intelligence — {escape(report.filename)}</h1>
    <div class="mut">{report.total_lines} lines ({report.ok_lines} resolved, {report.error_lines} errors) • currency {escape(report.currency)} • est. total {report.total_cost_estimate}</div>
    <div class="grid">
      <div class="card"><h2>Lifecycle distribution</h2>{dist or '<div class="mut">-</div>'}</div>
      <div class="card"><h2>Risk distribution</h2>{riskdist or '<div class="mut">-</div>'}</div>
    </div>
    <div class="card"><h2>Lines</h2><table><tr><th>#</th><th>Ref</th><th>MPN</th><th>Manufacturer</th><th>Qty</th><th>Lifecycle</th><th>Risk</th><th>Est. cost</th><th>Alternates</th><th>Notes</th></tr>{rows}</table></div>
    <div class="footer">Generated by Part Intelligence</div></div></body></html>"""
